
package com.ecommerce.ecommerce.modulo_banca_soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuarioService", targetNamespace = "modulo_banca_soap", wsdlLocation = "http://localhost:8082/?wsdl")
public class UsuarioService
    extends Service
{

    private final static URL USUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSERVICE_EXCEPTION;
    private final static QName USUARIOSERVICE_QNAME = new QName("modulo_banca_soap", "UsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSERVICE_WSDL_LOCATION = url;
        USUARIOSERVICE_EXCEPTION = e;
    }

    public UsuarioService() {
        super(__getWsdlLocation(), USUARIOSERVICE_QNAME);
    }

    public UsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSERVICE_QNAME, features);
    }

    public UsuarioService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSERVICE_QNAME);
    }

    public UsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSERVICE_QNAME, features);
    }

    public UsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(new QName("modulo_banca_soap", "Application"), Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(new QName("modulo_banca_soap", "Application"), Application.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSERVICE_EXCEPTION!= null) {
            throw USUARIOSERVICE_EXCEPTION;
        }
        return USUARIOSERVICE_WSDL_LOCATION;
    }

}
