export const ClientRoutes =  {
    HOME : "/",
    LOGIN : "/login",
    REGISTER : "/registro",
    PROFILE : "/profile",
    CART : "/cart",
    CHECKOUT : "/checkout",
    PRODUCT_DETAIL : "/product/:id",
    PRODUCTS_LIST : "/my/products",
    PRODUCT_CREATE : "/my/products/create",
    PRODUCT_MODIFY : "/my/products/edit/:id",
    ORDERS_LIST : "/my/orders",
    ORDER_DETAIL : "/my/orders/:id",
    CLAIMS_LIST : "/my/claims",
    CLAIM_LIST : "/my/claims/create",
}
